spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: true

server:
  port: 8080
  servlet:
    encoding:
      force-response: true
    session:
      timeout: 30m

logging:
  level:
    com.my.studyRecord: error
    org.springframework.security: error