server:
  port: 8081
  servlet:
    encoding:
      force-response: true
    session:
      timeout: 30m

logging:
  level:
    com.my.security3: trace
    org.springframework.security: debug

spring:
  profiles:
    include: secret

  thymeleaf:
    prefix: classpath:/templates/
    cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: none

    # JDBC TimeZone Setting
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true
        use_sql_comments: true

